Add api features to console logs for extra results information
5-gwoap/slng-node pull request #23
Opened 2018-01-19 10:16 UTC by jwu910

Added js api features to the console log

Edit: Fixes https://github.com/5-gwoap/slng-node/issues/19

2018-01-19 19:37 UTC, psyduc approved these changes
lgtm

2018-01-22 04:42 UTC, rainrivas requested changes
Magenta does not render on shells (ubuntu default, @psyduc to provide SS; and powershell, SS attached). 
The '=' split color was removed

2018-01-22 04:42 UTC, rainrivas commented on index.js
> +            console.log('Word: ' + chalk.magenta(result.word));
Magenta doesn't work on my powershell @jwu910

2018-01-22 04:42 UTC, rainrivas commented on index.js
> +      console.log('='.repeat(consoleWidth()));
We removed cyan from our split, was this on purpose?

2018-01-22 04:42 UTC, rainrivas commented on index.js
> +            console.log('Word: ' + chalk.magenta(result.word));
![image](https://user-images.githubusercontent.com/12107963/35205625-9081dbca-feeb-11e7-845f-c3a90932c74f.png)

2018-01-22 04:45 UTC, rainrivas commented on index.js
> +            console.log('Word: ' + chalk.magenta(result.word));
FYI highlighting does **not** help
![image](https://user-images.githubusercontent.com/12107963/35205677-f3ca0950-feeb-11e7-8ff4-960fe2aacbea.png)

2018-01-22 06:44 UTC, psyduc commented on index.js
> +            console.log('Word: ' + chalk.magenta(result.word));
![screenshot from 2018-01-21 22-43-27](https://user-images.githubusercontent.com/12107965/35208331-ae4242e2-fefc-11e7-83bf-8ae74799b1d2.png)

2018-02-03 08:19 UTC, rainrivas approved these changes

2018-02-03 08:19 UTC, rainrivas commented
@jwu910 if you cool with the color you can merge this to dev

2018-02-04 08:57 UTC, merged